name: Run main.py every 2 minutes

on:
  schedule:
    - cron: '*/2 * * * *'  # Runs every 2 minutes

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Replace with your Python version

      - name: Install dependencies
        run: |
          pip install requests

      - name: Run Python script
        run: python main.py  # Ensure this script outputs pta_nhi.json
        
