name: Run main.py every 2 minutes

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 2 minutes

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Replace with your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          

      - name: Run Python script
        run: python main.py  # Ensure this script outputs pta_nhi.json

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'PaytmKycAgent@gmail.com'
          git add pta_nhi.json
          git commit -m 'Update pta_nhi.json'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
